services:
  backend:
    container_name: backend
    image: shimady563/t1-debut-team5-backend:latest
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tech_radar
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_USERNAME=postgres
    depends_on:
      postgres:
        condition: service_healthy

  # fronted:
  #   container_name: frontend
  #   image: shimady563/t1-debut-team5-frontend:latest
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     backend:
  #       condition: service_started

  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tech_radar
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
