spring:
  application:
    name: techradar
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db-changelog-master.xml
logging:
  level:
    root: info
jwt:
  secret: 12ksafmkhdiucghdinusgnhu12ksafmkhdiucghdinusgnhu
  tokenLifeTime: 60000000000000
server:
  servlet:
    context-path: /api/v1