spring:
  application:
    name: techradar
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
    redis:
      time-to-live: 21600000
      enable-statistics: true
      cache-null-values: false
  liquibase:
    change-log: classpath:/db/changelog/db-changelog-master.xml
logging:
  level:
    root: info
jwt:
  secret: 12ksafmkhdiucghdinusgnhu12ksafmkhdiucghdinusgnhu
  tokenLifeTime: 86400000
server:
  servlet:
    context-path: /api/v1
auth:
  whitelist: /auth/**, /specializations, /swagger-ui.html, /v3/api-docs/**, /swagger-ui/**