spring:
  application:
    name: techradar
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
    redis:
      time-to-live: 21600000
      enable-statistics: true
      cache-null-values: false
  liquibase:
    change-log: classpath:/db/changelog/db-changelog-master.xml
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: technology
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            type:
              mapping: com.it.backend.dto.request.SkillTechRadarRequest:com.team5.techradar.model.dto.TechnologyPayload
logging:
  level:
    root: info
jwt:
  secret: 12ksafmkhdiucghdinusgnhu12ksafmkhdiucghdinusgnhu
  tokenLifeTime: 86400000
server:
  servlet:
    context-path: /api/v1
auth:
  whitelist: /auth/**, /swagger-ui.html, /v3/api-docs/**, /swagger-ui/**